### ISSUE TITLE
Feature Request: 60sweb

### ISSUE THREAD

**Issue by ghost** [s-dney/90sweb#5]
Hey I really love your work here, just wondering what is the possibility of you implementing a 60s version?

My favourite Beatle is George Harrison, so can you add heaps of photos of him and stuff? None of the others please because I don't like them.

Please and thanks

**Comment by ghost** [comment]
All good! Just realised that the internet wasn't around back then so that would've been silly!

**Comment by s-dney** [comment]
thomas, my friend. i will write you an extension that turns every photo on the internet into a picture of George Harrison if you find me your favorite pictures of him. the more the better.
