### ISSUE TITLE
Hey this is an issue

### ISSUE THREAD

**Issue by s-dney** [s-dney/90sweb#6]
This app sucks

**Comment by AshZhang** [comment]
![Screen Shot 2020-06-18 at 12 16 27](https://user-images.githubusercontent.com/20586063/85062661-b847a780-b15d-11ea-829b-6c0c1474f7bb.png)
Hmm, I can't seem to reproduce the problem. Looks perfectly 90s-spectacalicious to me. Have you tried turning it off and back on again?

**Comment by s-dney** [comment]
OMG ASHLEY im in a coding program rn and they had us create a github issue thru an API, so that was just my joke issue and I randomly chose this repository- Holy crap, I didn't even know if this would work anymore!!! I hope ur doing good
