### ISSUE TITLE
If you are still updating this

### ISSUE THREAD

**Issue by Darthskullshot** [s-dney/90sweb#7]
"Manifest version 2 is deprecated, and support will be removed in 2023" the error says, and if you want to fix this it would be cool. Cause I still really like using this lol. But I know it was just a project type thing or whatever.
![image](https://github.com/s-dney/90sweb/assets/109248782/e558f4b4-9427-4ff2-8d50-ae685a5d41c1)

**Comment by AshZhang** [comment]
Updated manifest to version 3.

I also see the audio play error, that is due to Chrome preventing audio from autoplaying on websites (https://developer.chrome.com/blog/autoplay/). Tracking issue here: https://github.com/s-dney/90sweb/issues/8
